### ISSUE TITLE
Commit Pull request

### ISSUE THREAD

**Issue by damtsnkff** [JakeLin/IBAnimatable-Material#1]
Hi guys !
Sorry for the dumb question, but I'm not familiar with Github at all and I pushed a commit to my fork instead of here. [Link here](https://github.com/damtsnkff/IBAnimatable-Material) in case. 
- Is it better to push a large commit at once, or is it better to commit "little" changes (a file)
- Do you have any advice for a beginner with the Github thing ?
  Thanks in advance.

**Comment by damtsnkff** [comment]
**Update**: I think I successfully pushed my commit. So before closing this, is normal that it added directly to the master branch ? 
_(thanks in advance)_

**Comment by tbaranes** [comment]
If you are not familiar with git / github, I suggests how to work with [git-flow](http://danielkummer.github.io/git-flow-cheatsheet/index.fr_FR.html). It's a nice practice to follow these guidelines, and it's also what we do in IBAnimatable.

About your fork, since you are a collaborator, you can directly create a new branch in the `IBAnimatable` repository (using a terminal, your git app...), but if you don't change your HEAD, it will be push to your default branch (which is `master`).

> Is it better to push a large commit at once, or is it better to commit "little" changes (a file)

It's better to push small commits which makes sense. Few commits are easier to review than a big one. You can take a look at `IBAnimatable` history, I won't say it's always perfect, but it's globally pretty good.

> Do you have any advice for a beginner with the Github thing ? Thanks in advance.

Just read some docs, and practices, github is really easy to use, you will be familiar with it fast enough! If you have any questions, just ask, we will be pleased to help you :)

> I pushed a commit to my fork instead of here

If you think that your new feature is ready to go, you can create a new [Pull Requests ](https://github.com/JakeLin/IBAnimatable-Material/compare) by targeting your [fork](https://help.github.com/articles/using-pull-requests/).

**Comment by damtsnkff** [comment]
@tbaranes thanks, I'm reading it now to avoid making this mistake in the future. 
Also, I think I pushed the commit without making a pull request.

**Comment by tbaranes** [comment]
If you don't do the PRs, it will available only in your fork and not in the main repository. Generally, for any new features, you have to fork or create a new branch in the repository, then create a PR for a review, then merge it in master (only at this moment, your feature will be available in the next release).

**Comment by JakeLin** [comment]
@tbaranes thanks for your detailed explanations. 

@damtsnkff don't stress about it; please speak out if you have any questions. Everyone (at least myself) makes mistakes, and that's why we use git. Most likely we can come back to the history and redo it if we make mistakes.

There is a GitHub process we are using now. 
1. We are using feature branches to work on new features and PR to master. e.g. feature/animatable-flat-button
2. we are using bugfix branches to fix bugs then PR to master. e.g. bugfix/fix-material-color

Branches should be small but fully functional.  And we can check each others PR before we can merge to master.

Let's take an example, for example, if we develop a new feature called material flat button. There will be few steps.

Since you are a collaborator, you can create a new branch. 
1. `git checkout master` to checkout master
2. `git pull origin master` to get all updates from master
3. `git checkout -b feature/animatable-flat-button` to create a new branch called feature/animatable-flat-button
4. Add a new class called `AnimatableFlatButton` and develop the feature. That can be one commit since it is a fully functional feature.
5. Add a Scene in storyboard and add a test ViewController for the test Scene (we may not need it for this case). That can be another commit. A commit would be an atom feature set. It can be a single file, or a set of files to perform a completed feature or a bugfix. Think about if we want to check the history or do something wrong, then what's the useful information we can track back and lock up the changes. What's the checkpoint (commit) we can rollback or reset?
6. Once we test this feature, then we can create a PR from feature/animatable-flat-button to master.
7. Then we can review each others PR, and make comments on the PR.
8. We can discuss the PR or make changes to address the comments.
9. Once we are OK, then we can merge this PR to master and delete the branch e.g.  feature/animatable-flat-button in this case.

Please feel free to ask any questions.

**Comment by damtsnkff** [comment]
Waw, thanks for the thorough explanation! I'll definitely follow this process that makes everything more organized. 
Also, thank you both for taking the time to explain it. I'm looking forward to use it and practice. :)
